apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-app
  name: {{ .Values.service.name }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    app: node-app
  type: {{ .Values.service.type }}